" quate: quiet greys, gruvbox weights, a mint glow.
"
"   :colorscheme quate
"
" GENERATED by scripts/gen_vim.lua -- do not edit. Re-run:
"
"   nvim -l scripts/gen_vim.lua > colors/quate.vim
"
" Neovim keeps the Lua path, with every option and every treesitter and
" diagnostic group. This file is the Vim 8.2+/9 subset: the options are
" frozen at the defaults and the `@...` groups are gone, since Vim has
" neither.

if has("nvim")
  lua require('quate').load()
  finish
endif

set background=dark
hi clear
if exists("syntax_on")
  syntax reset
endif
let g:colors_name = 'quate'

hi Added term=NONE gui=NONE cterm=NONE guifg=#1bfd9c ctermfg=49 guibg=NONE ctermbg=NONE guisp=NONE
hi BlinkCmpGhostText term=italic gui=italic cterm=italic guifg=#4e4e4e ctermfg=239 guibg=NONE ctermbg=NONE guisp=NONE
hi BlinkCmpKind term=NONE gui=NONE cterm=NONE guifg=#707070 ctermfg=242 guibg=NONE ctermbg=NONE guisp=NONE
hi BlinkCmpLabelDeprecated term=strikethrough gui=strikethrough cterm=strikethrough guifg=#707070 ctermfg=242 guibg=NONE ctermbg=NONE guisp=NONE
hi BlinkCmpLabelMatch term=bold gui=bold cterm=bold guifg=#1bfd9c ctermfg=49 guibg=NONE ctermbg=NONE guisp=NONE
hi! link BlinkCmpMenu Pmenu
hi! link BlinkCmpMenuBorder FloatBorder
hi! link BlinkCmpMenuSelection PmenuSel
hi Bold term=bold gui=bold cterm=bold guifg=NONE ctermfg=NONE guibg=NONE ctermbg=NONE guisp=NONE
hi! link Boolean Constant
hi Changed term=NONE gui=NONE cterm=NONE guifg=#a8a8a8 ctermfg=248 guibg=NONE ctermbg=NONE guisp=NONE
hi! link Character Constant
hi CmpItemAbbr term=NONE gui=NONE cterm=NONE guifg=#dadada ctermfg=253 guibg=NONE ctermbg=NONE guisp=NONE
hi CmpItemAbbrDeprecated term=strikethrough gui=strikethrough cterm=strikethrough guifg=#707070 ctermfg=242 guibg=NONE ctermbg=NONE guisp=NONE
hi CmpItemAbbrMatch term=bold gui=bold cterm=bold guifg=#1bfd9c ctermfg=49 guibg=NONE ctermbg=NONE guisp=NONE
hi CmpItemAbbrMatchFuzzy term=bold gui=bold cterm=bold guifg=#00d7af ctermfg=43 guibg=NONE ctermbg=NONE guisp=NONE
hi CmpItemKind term=NONE gui=NONE cterm=NONE guifg=#707070 ctermfg=242 guibg=NONE ctermbg=NONE guisp=NONE
hi CmpItemMenu term=italic gui=italic cterm=italic guifg=#4e4e4e ctermfg=239 guibg=NONE ctermbg=NONE guisp=NONE
hi ColorColumn term=NONE gui=NONE cterm=NONE guifg=NONE ctermfg=NONE guibg=#1c1c1c ctermbg=234 guisp=NONE
hi Comment term=italic gui=italic cterm=italic guifg=#707070 ctermfg=242 guibg=NONE ctermbg=NONE guisp=NONE
hi ComplMatchIns term=NONE gui=NONE cterm=NONE guifg=#707070 ctermfg=242 guibg=NONE ctermbg=NONE guisp=NONE
hi Conceal term=NONE gui=NONE cterm=NONE guifg=#707070 ctermfg=242 guibg=NONE ctermbg=NONE guisp=NONE
hi! link Conditional Statement
hi Constant term=NONE gui=NONE cterm=NONE guifg=#dadada ctermfg=253 guibg=NONE ctermbg=NONE guisp=NONE
hi! link CurSearch IncSearch
hi Cursor term=reverse gui=reverse cterm=reverse guifg=NONE ctermfg=NONE guibg=NONE ctermbg=NONE guisp=NONE
hi CursorColumn term=NONE gui=NONE cterm=NONE guifg=NONE ctermfg=NONE guibg=#1c1c1c ctermbg=234 guisp=NONE
hi! link CursorIM Cursor
hi CursorLine term=NONE gui=NONE cterm=NONE guifg=NONE ctermfg=NONE guibg=#1c1c1c ctermbg=234 guisp=NONE
hi! link CursorLineFold FoldColumn
hi CursorLineNr term=bold gui=bold cterm=bold guifg=#1bfd9c ctermfg=49 guibg=NONE ctermbg=NONE guisp=NONE
hi! link CursorLineSign SignColumn
hi Debug term=NONE gui=NONE cterm=NONE guifg=#1bfd9c ctermfg=49 guibg=NONE ctermbg=NONE guisp=NONE
hi! link Define PreProc
hi Delimiter term=NONE gui=NONE cterm=NONE guifg=#a8a8a8 ctermfg=248 guibg=NONE ctermbg=NONE guisp=NONE
hi DiagnosticDeprecated term=strikethrough gui=strikethrough cterm=strikethrough guifg=#707070 ctermfg=242 guibg=NONE ctermbg=NONE guisp=NONE
hi DiagnosticError term=bold gui=bold cterm=bold guifg=#ffffff ctermfg=231 guibg=NONE ctermbg=NONE guisp=NONE
hi! link DiagnosticFloatingError DiagnosticError
hi! link DiagnosticFloatingHint DiagnosticHint
hi! link DiagnosticFloatingInfo DiagnosticInfo
hi! link DiagnosticFloatingOk DiagnosticOk
hi! link DiagnosticFloatingWarn DiagnosticWarn
hi DiagnosticHint term=italic gui=italic cterm=italic guifg=#707070 ctermfg=242 guibg=NONE ctermbg=NONE guisp=NONE
hi DiagnosticInfo term=NONE gui=NONE cterm=NONE guifg=#707070 ctermfg=242 guibg=NONE ctermbg=NONE guisp=NONE
hi DiagnosticOk term=NONE gui=NONE cterm=NONE guifg=#1bfd9c ctermfg=49 guibg=NONE ctermbg=NONE guisp=NONE
hi! link DiagnosticSignError DiagnosticError
hi! link DiagnosticSignHint DiagnosticHint
hi! link DiagnosticSignInfo DiagnosticInfo
hi! link DiagnosticSignOk DiagnosticOk
hi! link DiagnosticSignWarn DiagnosticWarn
hi DiagnosticUnderlineError term=undercurl gui=undercurl cterm=undercurl guifg=NONE ctermfg=NONE guibg=NONE ctermbg=NONE guisp=#ffffff
hi DiagnosticUnderlineHint term=underdotted gui=underdotted cterm=underdotted guifg=NONE ctermfg=NONE guibg=NONE ctermbg=NONE guisp=#4e4e4e
hi DiagnosticUnderlineInfo term=underdotted gui=underdotted cterm=underdotted guifg=NONE ctermfg=NONE guibg=NONE ctermbg=NONE guisp=#707070
hi DiagnosticUnderlineOk term=undercurl gui=undercurl cterm=undercurl guifg=NONE ctermfg=NONE guibg=NONE ctermbg=NONE guisp=#00d7af
hi DiagnosticUnderlineWarn term=underdashed gui=underdashed cterm=underdashed guifg=NONE ctermfg=NONE guibg=NONE ctermbg=NONE guisp=#a8a8a8
hi DiagnosticUnnecessary term=italic gui=italic cterm=italic guifg=#4e4e4e ctermfg=239 guibg=NONE ctermbg=NONE guisp=NONE
hi DiagnosticVirtualTextError term=bold gui=bold cterm=bold guifg=#a8a8a8 ctermfg=248 guibg=NONE ctermbg=NONE guisp=NONE
hi DiagnosticVirtualTextHint term=italic gui=italic cterm=italic guifg=#4e4e4e ctermfg=239 guibg=NONE ctermbg=NONE guisp=NONE
hi DiagnosticVirtualTextInfo term=NONE gui=NONE cterm=NONE guifg=#4e4e4e ctermfg=239 guibg=NONE ctermbg=NONE guisp=NONE
hi DiagnosticVirtualTextOk term=NONE gui=NONE cterm=NONE guifg=#00d7af ctermfg=43 guibg=NONE ctermbg=NONE guisp=NONE
hi DiagnosticVirtualTextWarn term=NONE gui=NONE cterm=NONE guifg=#707070 ctermfg=242 guibg=NONE ctermbg=NONE guisp=NONE
hi DiagnosticWarn term=NONE gui=NONE cterm=NONE guifg=#a8a8a8 ctermfg=248 guibg=NONE ctermbg=NONE guisp=NONE
hi DiffAdd term=NONE gui=NONE cterm=NONE guifg=NONE ctermfg=NONE guibg=#10241c ctermbg=22 guisp=NONE
hi DiffChange term=NONE gui=NONE cterm=NONE guifg=NONE ctermfg=NONE guibg=#1a1a1a ctermbg=235 guisp=NONE
hi DiffDelete term=NONE gui=NONE cterm=NONE guifg=#4e4e4e ctermfg=239 guibg=#141414 ctermbg=233 guisp=NONE
hi DiffText term=bold gui=bold cterm=bold guifg=NONE ctermfg=NONE guibg=#1f4034 ctermbg=23 guisp=NONE
hi Directory term=bold gui=bold cterm=bold guifg=#dadada ctermfg=253 guibg=NONE ctermbg=NONE guisp=NONE
hi EndOfBuffer term=NONE gui=NONE cterm=NONE guifg=#4e4e4e ctermfg=239 guibg=NONE ctermbg=NONE guisp=NONE
hi Error term=bold,reverse gui=bold,reverse cterm=bold,reverse guifg=#ffffff ctermfg=231 guibg=#000000 ctermbg=16 guisp=NONE
hi ErrorMsg term=bold gui=bold cterm=bold guifg=#ffffff ctermfg=231 guibg=NONE ctermbg=NONE guisp=NONE
hi! link Exception Statement
hi FlashLabel term=bold gui=bold cterm=bold guifg=#000000 ctermfg=16 guibg=#87ffd7 ctermbg=122 guisp=NONE
hi! link Float Constant
hi FloatBorder term=NONE gui=NONE cterm=NONE guifg=#3a3a3a ctermfg=237 guibg=#121212 ctermbg=233 guisp=NONE
hi FloatFooter term=NONE gui=NONE cterm=NONE guifg=#707070 ctermfg=242 guibg=#121212 ctermbg=233 guisp=NONE
hi FloatTitle term=bold gui=bold cterm=bold guifg=#dadada ctermfg=253 guibg=#121212 ctermbg=233 guisp=NONE
hi FoldColumn term=NONE gui=NONE cterm=NONE guifg=#4e4e4e ctermfg=239 guibg=#000000 ctermbg=16 guisp=NONE
hi Folded term=italic gui=italic cterm=italic guifg=#707070 ctermfg=242 guibg=#121212 ctermbg=233 guisp=NONE
hi Function term=bold gui=bold cterm=bold guifg=#dadada ctermfg=253 guibg=NONE ctermbg=NONE guisp=NONE
hi GitSignsAdd term=NONE gui=NONE cterm=NONE guifg=#00d7af ctermfg=43 guibg=NONE ctermbg=NONE guisp=NONE
hi GitSignsAddInline term=NONE gui=NONE cterm=NONE guifg=NONE ctermfg=NONE guibg=#1f4034 ctermbg=23 guisp=NONE
hi GitSignsChange term=NONE gui=NONE cterm=NONE guifg=#a8a8a8 ctermfg=248 guibg=NONE ctermbg=NONE guisp=NONE
hi GitSignsChangeInline term=NONE gui=NONE cterm=NONE guifg=NONE ctermfg=NONE guibg=#1a1a1a ctermbg=235 guisp=NONE
hi GitSignsCurrentLineBlame term=italic gui=italic cterm=italic guifg=#4e4e4e ctermfg=239 guibg=NONE ctermbg=NONE guisp=NONE
hi GitSignsDelete term=NONE gui=NONE cterm=NONE guifg=#707070 ctermfg=242 guibg=NONE ctermbg=NONE guisp=NONE
hi GitSignsDeleteInline term=NONE gui=NONE cterm=NONE guifg=#4e4e4e ctermfg=239 guibg=#141414 ctermbg=233 guisp=NONE
hi IblIndent term=NONE gui=NONE cterm=NONE guifg=#303030 ctermfg=236 guibg=NONE ctermbg=NONE guisp=NONE
hi IblScope term=NONE gui=NONE cterm=NONE guifg=#3a3a3a ctermfg=237 guibg=NONE ctermbg=NONE guisp=NONE
hi IblWhitespace term=NONE gui=NONE cterm=NONE guifg=#1c1c1c ctermfg=234 guibg=NONE ctermbg=NONE guisp=NONE
hi Identifier term=bold gui=bold cterm=bold guifg=#dadada ctermfg=253 guibg=NONE ctermbg=NONE guisp=NONE
hi Ignore term=NONE gui=NONE cterm=NONE guifg=#4e4e4e ctermfg=239 guibg=NONE ctermbg=NONE guisp=NONE
hi IncSearch term=bold gui=bold cterm=bold guifg=#000000 ctermfg=16 guibg=#1bfd9c ctermbg=49 guisp=NONE
hi! link Include PreProc
hi Italic term=italic gui=italic cterm=italic guifg=NONE ctermfg=NONE guibg=NONE ctermbg=NONE guisp=NONE
hi! link Keyword Statement
hi! link Label Statement
hi LazyButtonActive term=bold gui=bold cterm=bold guifg=#1bfd9c ctermfg=49 guibg=#303030 ctermbg=236 guisp=NONE
hi LazyH1 term=bold gui=bold cterm=bold guifg=#ffffff ctermfg=231 guibg=#303030 ctermbg=236 guisp=NONE
hi LazyNormal term=NONE gui=NONE cterm=NONE guifg=#dadada ctermfg=253 guibg=#121212 ctermbg=233 guisp=NONE
hi LazyProgressDone term=bold gui=bold cterm=bold guifg=#1bfd9c ctermfg=49 guibg=NONE ctermbg=NONE guisp=NONE
hi LazyProgressTodo term=NONE gui=NONE cterm=NONE guifg=#4e4e4e ctermfg=239 guibg=NONE ctermbg=NONE guisp=NONE
hi LineNr term=NONE gui=NONE cterm=NONE guifg=#4e4e4e ctermfg=239 guibg=NONE ctermbg=NONE guisp=NONE
hi! link LineNrAbove LineNr
hi! link LineNrBelow LineNr
hi LspCodeLens term=italic gui=italic cterm=italic guifg=#4e4e4e ctermfg=239 guibg=NONE ctermbg=NONE guisp=NONE
hi LspCodeLensSeparator term=NONE gui=NONE cterm=NONE guifg=#4e4e4e ctermfg=239 guibg=NONE ctermbg=NONE guisp=NONE
hi! link LspInfoBorder FloatBorder
hi LspInlayHint term=italic gui=italic cterm=italic guifg=#4e4e4e ctermfg=239 guibg=#1c1c1c ctermbg=234 guisp=NONE
hi LspReferenceRead term=NONE gui=NONE cterm=NONE guifg=NONE ctermfg=NONE guibg=#1c1c1c ctermbg=234 guisp=NONE
hi LspReferenceTarget term=NONE gui=NONE cterm=NONE guifg=NONE ctermfg=NONE guibg=#1c1c1c ctermbg=234 guisp=NONE
hi LspReferenceText term=NONE gui=NONE cterm=NONE guifg=NONE ctermfg=NONE guibg=#1c1c1c ctermbg=234 guisp=NONE
hi LspReferenceWrite term=underline gui=underline cterm=underline guifg=NONE ctermfg=NONE guibg=#1c1c1c ctermbg=234 guisp=#00d7af
hi LspSignatureActiveParameter term=bold gui=bold cterm=bold guifg=#1bfd9c ctermfg=49 guibg=NONE ctermbg=NONE guisp=NONE
hi! link Macro PreProc
hi MasonHeader term=bold gui=bold cterm=bold guifg=#ffffff ctermfg=231 guibg=#303030 ctermbg=236 guisp=NONE
hi MasonHighlight term=NONE gui=NONE cterm=NONE guifg=#1bfd9c ctermfg=49 guibg=NONE ctermbg=NONE guisp=NONE
hi MasonMuted term=NONE gui=NONE cterm=NONE guifg=#707070 ctermfg=242 guibg=NONE ctermbg=NONE guisp=NONE
hi MasonNormal term=NONE gui=NONE cterm=NONE guifg=#dadada ctermfg=253 guibg=#121212 ctermbg=233 guisp=NONE
hi MatchParen term=bold gui=bold cterm=bold guifg=#87ffd7 ctermfg=122 guibg=NONE ctermbg=NONE guisp=NONE
hi MiniCursorword term=NONE gui=NONE cterm=NONE guifg=NONE ctermfg=NONE guibg=#1c1c1c ctermbg=234 guisp=NONE
hi MiniCursorwordCurrent term=NONE gui=NONE cterm=NONE guifg=NONE ctermfg=NONE guibg=#1c1c1c ctermbg=234 guisp=NONE
hi MiniDiffSignAdd term=NONE gui=NONE cterm=NONE guifg=#00d7af ctermfg=43 guibg=NONE ctermbg=NONE guisp=NONE
hi MiniDiffSignChange term=NONE gui=NONE cterm=NONE guifg=#a8a8a8 ctermfg=248 guibg=NONE ctermbg=NONE guisp=NONE
hi MiniDiffSignDelete term=NONE gui=NONE cterm=NONE guifg=#707070 ctermfg=242 guibg=NONE ctermbg=NONE guisp=NONE
hi MiniIndentscopeSymbol term=NONE gui=NONE cterm=NONE guifg=#3a3a3a ctermfg=237 guibg=NONE ctermbg=NONE guisp=NONE
hi! link MiniPickMatchCurrent PmenuSel
hi MiniPickMatchRanges term=bold gui=bold cterm=bold guifg=#1bfd9c ctermfg=49 guibg=NONE ctermbg=NONE guisp=NONE
hi MiniStatuslineDevinfo term=NONE gui=NONE cterm=NONE guifg=#a8a8a8 ctermfg=248 guibg=#1c1c1c ctermbg=234 guisp=NONE
hi MiniStatuslineFilename term=NONE gui=NONE cterm=NONE guifg=#707070 ctermfg=242 guibg=#121212 ctermbg=233 guisp=NONE
hi MiniStatuslineInactive term=NONE gui=NONE cterm=NONE guifg=#707070 ctermfg=242 guibg=#121212 ctermbg=233 guisp=NONE
hi MiniStatuslineModeCommand term=bold gui=bold cterm=bold guifg=#000000 ctermfg=16 guibg=#a8a8a8 ctermbg=248 guisp=NONE
hi MiniStatuslineModeInsert term=bold gui=bold cterm=bold guifg=#000000 ctermfg=16 guibg=#dadada ctermbg=253 guisp=NONE
hi MiniStatuslineModeNormal term=bold gui=bold cterm=bold guifg=#000000 ctermfg=16 guibg=#1bfd9c ctermbg=49 guisp=NONE
hi MiniStatuslineModeOther term=bold gui=bold cterm=bold guifg=#000000 ctermfg=16 guibg=#707070 ctermbg=242 guisp=NONE
hi MiniStatuslineModeReplace term=bold gui=bold cterm=bold guifg=#000000 ctermfg=16 guibg=#00d7af ctermbg=43 guisp=NONE
hi MiniStatuslineModeVisual term=bold gui=bold cterm=bold guifg=#000000 ctermfg=16 guibg=#a8a8a8 ctermbg=248 guisp=NONE
hi ModeMsg term=bold gui=bold cterm=bold guifg=#1bfd9c ctermfg=49 guibg=NONE ctermbg=NONE guisp=NONE
hi MoreMsg term=NONE gui=NONE cterm=NONE guifg=#a8a8a8 ctermfg=248 guibg=NONE ctermbg=NONE guisp=NONE
hi MsgArea term=NONE gui=NONE cterm=NONE guifg=#dadada ctermfg=253 guibg=NONE ctermbg=NONE guisp=NONE
hi MsgSeparator term=NONE gui=NONE cterm=NONE guifg=#3a3a3a ctermfg=237 guibg=#121212 ctermbg=233 guisp=NONE
hi NeoTreeDirectoryName term=NONE gui=NONE cterm=NONE guifg=#a8a8a8 ctermfg=248 guibg=NONE ctermbg=NONE guisp=NONE
hi NeoTreeGitAdded term=NONE gui=NONE cterm=NONE guifg=#00d7af ctermfg=43 guibg=NONE ctermbg=NONE guisp=NONE
hi NeoTreeGitDeleted term=NONE gui=NONE cterm=NONE guifg=#707070 ctermfg=242 guibg=NONE ctermbg=NONE guisp=NONE
hi NeoTreeGitModified term=NONE gui=NONE cterm=NONE guifg=#a8a8a8 ctermfg=248 guibg=NONE ctermbg=NONE guisp=NONE
hi NeoTreeIndentMarker term=NONE gui=NONE cterm=NONE guifg=#303030 ctermfg=236 guibg=NONE ctermbg=NONE guisp=NONE
hi NeoTreeNormal term=NONE gui=NONE cterm=NONE guifg=#dadada ctermfg=253 guibg=#121212 ctermbg=233 guisp=NONE
hi NeoTreeRootName term=bold gui=bold cterm=bold guifg=#dadada ctermfg=253 guibg=NONE ctermbg=NONE guisp=NONE
hi NonText term=NONE gui=NONE cterm=NONE guifg=#4e4e4e ctermfg=239 guibg=NONE ctermbg=NONE guisp=NONE
hi Normal term=NONE gui=NONE cterm=NONE guifg=#dadada ctermfg=253 guibg=#000000 ctermbg=16 guisp=NONE
hi NormalFloat term=NONE gui=NONE cterm=NONE guifg=#dadada ctermfg=253 guibg=#121212 ctermbg=233 guisp=NONE
hi! link NormalNC Normal
hi NotifyERRORTitle term=bold gui=bold cterm=bold guifg=#ffffff ctermfg=231 guibg=NONE ctermbg=NONE guisp=NONE
hi NotifyINFOTitle term=NONE gui=NONE cterm=NONE guifg=#1bfd9c ctermfg=49 guibg=NONE ctermbg=NONE guisp=NONE
hi NotifyWARNTitle term=NONE gui=NONE cterm=NONE guifg=#a8a8a8 ctermfg=248 guibg=NONE ctermbg=NONE guisp=NONE
hi! link Number Constant
hi NvimTreeFolderName term=NONE gui=NONE cterm=NONE guifg=#a8a8a8 ctermfg=248 guibg=NONE ctermbg=NONE guisp=NONE
hi NvimTreeGitDeleted term=NONE gui=NONE cterm=NONE guifg=#707070 ctermfg=242 guibg=NONE ctermbg=NONE guisp=NONE
hi NvimTreeGitDirty term=NONE gui=NONE cterm=NONE guifg=#a8a8a8 ctermfg=248 guibg=NONE ctermbg=NONE guisp=NONE
hi NvimTreeGitNew term=NONE gui=NONE cterm=NONE guifg=#00d7af ctermfg=43 guibg=NONE ctermbg=NONE guisp=NONE
hi NvimTreeIndentMarker term=NONE gui=NONE cterm=NONE guifg=#303030 ctermfg=236 guibg=NONE ctermbg=NONE guisp=NONE
hi NvimTreeNormal term=NONE gui=NONE cterm=NONE guifg=#dadada ctermfg=253 guibg=#121212 ctermbg=233 guisp=NONE
hi NvimTreeOpenedFolderName term=bold gui=bold cterm=bold guifg=#dadada ctermfg=253 guibg=NONE ctermbg=NONE guisp=NONE
hi NvimTreeRootFolder term=bold gui=bold cterm=bold guifg=#dadada ctermfg=253 guibg=NONE ctermbg=NONE guisp=NONE
hi NvimTreeSpecialFile term=NONE gui=NONE cterm=NONE guifg=#1bfd9c ctermfg=49 guibg=NONE ctermbg=NONE guisp=NONE
hi OilDir term=NONE gui=NONE cterm=NONE guifg=#a8a8a8 ctermfg=248 guibg=NONE ctermbg=NONE guisp=NONE
hi OilFile term=NONE gui=NONE cterm=NONE guifg=#dadada ctermfg=253 guibg=NONE ctermbg=NONE guisp=NONE
hi Operator term=bold gui=bold cterm=bold guifg=#1bfd9c ctermfg=49 guibg=NONE ctermbg=NONE guisp=NONE
hi Pmenu term=NONE gui=NONE cterm=NONE guifg=#dadada ctermfg=253 guibg=#1c1c1c ctermbg=234 guisp=NONE
hi PmenuExtra term=NONE gui=NONE cterm=NONE guifg=#707070 ctermfg=242 guibg=#1c1c1c ctermbg=234 guisp=NONE
hi PmenuExtraSel term=NONE gui=NONE cterm=NONE guifg=#a8a8a8 ctermfg=248 guibg=#303030 ctermbg=236 guisp=NONE
hi PmenuKind term=bold gui=bold cterm=bold guifg=#707070 ctermfg=242 guibg=#1c1c1c ctermbg=234 guisp=NONE
hi PmenuKindSel term=bold gui=bold cterm=bold guifg=#707070 ctermfg=242 guibg=#303030 ctermbg=236 guisp=NONE
hi PmenuMatch term=bold gui=bold cterm=bold guifg=#1bfd9c ctermfg=49 guibg=#1c1c1c ctermbg=234 guisp=NONE
hi PmenuMatchSel term=bold gui=bold cterm=bold guifg=#87ffd7 ctermfg=122 guibg=#303030 ctermbg=236 guisp=NONE
hi PmenuSbar term=NONE gui=NONE cterm=NONE guifg=NONE ctermfg=NONE guibg=#1c1c1c ctermbg=234 guisp=NONE
hi PmenuSel term=bold gui=bold cterm=bold guifg=#000000 ctermfg=16 guibg=#1bfd9c ctermbg=49 guisp=NONE
hi PmenuThumb term=NONE gui=NONE cterm=NONE guifg=NONE ctermfg=NONE guibg=#3a3a3a ctermbg=237 guisp=NONE
hi! link PreCondit PreProc
hi PreProc term=NONE gui=NONE cterm=NONE guifg=#a8a8a8 ctermfg=248 guibg=NONE ctermbg=NONE guisp=NONE
hi Question term=NONE gui=NONE cterm=NONE guifg=#1bfd9c ctermfg=49 guibg=NONE ctermbg=NONE guisp=NONE
hi QuickFixLine term=bold gui=bold cterm=bold guifg=NONE ctermfg=NONE guibg=#303030 ctermbg=236 guisp=NONE
hi RainbowDelimiter1 term=NONE gui=NONE cterm=NONE guifg=#a8a8a8 ctermfg=248 guibg=NONE ctermbg=NONE guisp=NONE
hi RainbowDelimiter2 term=NONE gui=NONE cterm=NONE guifg=#707070 ctermfg=242 guibg=NONE ctermbg=NONE guisp=NONE
hi RainbowDelimiter3 term=NONE gui=NONE cterm=NONE guifg=#00d7af ctermfg=43 guibg=NONE ctermbg=NONE guisp=NONE
hi Removed term=NONE gui=NONE cterm=NONE guifg=#707070 ctermfg=242 guibg=NONE ctermbg=NONE guisp=NONE
hi! link Repeat Statement
hi Search term=bold gui=bold cterm=bold guifg=#1bfd9c ctermfg=49 guibg=NONE ctermbg=NONE guisp=NONE
hi SignColumn term=NONE gui=NONE cterm=NONE guifg=#4e4e4e ctermfg=239 guibg=#000000 ctermbg=16 guisp=NONE
hi SnippetTabstop term=NONE gui=NONE cterm=NONE guifg=NONE ctermfg=NONE guibg=#303030 ctermbg=236 guisp=NONE
hi Special term=NONE gui=NONE cterm=NONE guifg=#1bfd9c ctermfg=49 guibg=NONE ctermbg=NONE guisp=NONE
hi SpecialChar term=NONE gui=NONE cterm=NONE guifg=#1bfd9c ctermfg=49 guibg=NONE ctermbg=NONE guisp=NONE
hi SpecialComment term=bold,italic gui=bold,italic cterm=bold,italic guifg=#707070 ctermfg=242 guibg=NONE ctermbg=NONE guisp=NONE
hi SpecialKey term=NONE gui=NONE cterm=NONE guifg=#707070 ctermfg=242 guibg=NONE ctermbg=NONE guisp=NONE
hi SpellBad term=undercurl gui=undercurl cterm=undercurl guifg=NONE ctermfg=NONE guibg=NONE ctermbg=NONE guisp=#ffffff
hi SpellCap term=underdashed gui=underdashed cterm=underdashed guifg=NONE ctermfg=NONE guibg=NONE ctermbg=NONE guisp=#a8a8a8
hi SpellLocal term=underdotted gui=underdotted cterm=underdotted guifg=NONE ctermfg=NONE guibg=NONE ctermbg=NONE guisp=#707070
hi SpellRare term=underdotted gui=underdotted cterm=underdotted guifg=NONE ctermfg=NONE guibg=NONE ctermbg=NONE guisp=#00d7af
hi Statement term=bold gui=bold cterm=bold guifg=#dadada ctermfg=253 guibg=NONE ctermbg=NONE guisp=NONE
hi StatusLine term=bold gui=bold cterm=bold guifg=#dadada ctermfg=253 guibg=#121212 ctermbg=233 guisp=NONE
hi StatusLineNC term=NONE gui=NONE cterm=NONE guifg=#707070 ctermfg=242 guibg=#121212 ctermbg=233 guisp=NONE
hi StatusLineTerm term=bold gui=bold cterm=bold guifg=#1bfd9c ctermfg=49 guibg=#121212 ctermbg=233 guisp=NONE
hi StatusLineTermNC term=NONE gui=NONE cterm=NONE guifg=#00d7af ctermfg=43 guibg=#121212 ctermbg=233 guisp=NONE
hi StorageClass term=bold gui=bold cterm=bold guifg=#dadada ctermfg=253 guibg=NONE ctermbg=NONE guisp=NONE
hi String term=NONE gui=NONE cterm=NONE guifg=#dadada ctermfg=253 guibg=NONE ctermbg=NONE guisp=NONE
hi! link Structure StorageClass
hi! link Substitute IncSearch
hi TabLine term=NONE gui=NONE cterm=NONE guifg=#707070 ctermfg=242 guibg=#121212 ctermbg=233 guisp=NONE
hi TabLineFill term=NONE gui=NONE cterm=NONE guifg=NONE ctermfg=NONE guibg=#121212 ctermbg=233 guisp=NONE
hi TabLineSel term=bold gui=bold cterm=bold guifg=#dadada ctermfg=253 guibg=#000000 ctermbg=16 guisp=NONE
hi Tag term=bold gui=bold cterm=bold guifg=#dadada ctermfg=253 guibg=NONE ctermbg=NONE guisp=NONE
hi TelescopeBorder term=NONE gui=NONE cterm=NONE guifg=#3a3a3a ctermfg=237 guibg=#121212 ctermbg=233 guisp=NONE
hi TelescopeMatching term=bold gui=bold cterm=bold guifg=#1bfd9c ctermfg=49 guibg=NONE ctermbg=NONE guisp=NONE
hi TelescopeMultiSelection term=NONE gui=NONE cterm=NONE guifg=#1bfd9c ctermfg=49 guibg=NONE ctermbg=NONE guisp=NONE
hi TelescopeNormal term=NONE gui=NONE cterm=NONE guifg=#dadada ctermfg=253 guibg=#121212 ctermbg=233 guisp=NONE
hi TelescopePromptCounter term=NONE gui=NONE cterm=NONE guifg=#707070 ctermfg=242 guibg=NONE ctermbg=NONE guisp=NONE
hi TelescopePromptTitle term=bold gui=bold cterm=bold guifg=#1bfd9c ctermfg=49 guibg=NONE ctermbg=NONE guisp=NONE
hi TelescopeSelection term=bold gui=bold cterm=bold guifg=#ffffff ctermfg=231 guibg=#303030 ctermbg=236 guisp=NONE
hi TelescopeSelectionCaret term=NONE gui=NONE cterm=NONE guifg=#1bfd9c ctermfg=49 guibg=#303030 ctermbg=236 guisp=NONE
hi TelescopeTitle term=bold gui=bold cterm=bold guifg=#dadada ctermfg=253 guibg=NONE ctermbg=NONE guisp=NONE
hi! link TermCursor Cursor
hi TermCursorNC term=NONE gui=NONE cterm=NONE guifg=NONE ctermfg=NONE guibg=#303030 ctermbg=236 guisp=NONE
hi Title term=bold gui=bold cterm=bold guifg=#dadada ctermfg=253 guibg=NONE ctermbg=NONE guisp=NONE
hi Todo term=bold,italic,reverse gui=bold,italic,reverse cterm=bold,italic,reverse guifg=#1bfd9c ctermfg=49 guibg=#000000 ctermbg=16 guisp=NONE
hi TreesitterContext term=NONE gui=NONE cterm=NONE guifg=NONE ctermfg=NONE guibg=#1c1c1c ctermbg=234 guisp=NONE
hi TreesitterContextLineNumber term=NONE gui=NONE cterm=NONE guifg=#4e4e4e ctermfg=239 guibg=#1c1c1c ctermbg=234 guisp=NONE
hi Type term=NONE gui=NONE cterm=NONE guifg=#dadada ctermfg=253 guibg=NONE ctermbg=NONE guisp=NONE
hi! link Typedef StorageClass
hi Underlined term=underline gui=underline cterm=underline guifg=#dadada ctermfg=253 guibg=NONE ctermbg=NONE guisp=NONE
hi! link VertSplit WinSeparator
hi Visual term=NONE gui=NONE cterm=NONE guifg=NONE ctermfg=NONE guibg=#303030 ctermbg=236 guisp=NONE
hi VisualNOS term=NONE gui=NONE cterm=NONE guifg=NONE ctermfg=NONE guibg=#1c1c1c ctermbg=234 guisp=NONE
hi WarningMsg term=NONE gui=NONE cterm=NONE guifg=#a8a8a8 ctermfg=248 guibg=NONE ctermbg=NONE guisp=NONE
hi WhichKey term=bold gui=bold cterm=bold guifg=#1bfd9c ctermfg=49 guibg=NONE ctermbg=NONE guisp=NONE
hi! link WhichKeyBorder FloatBorder
hi WhichKeyDesc term=NONE gui=NONE cterm=NONE guifg=#dadada ctermfg=253 guibg=NONE ctermbg=NONE guisp=NONE
hi WhichKeyFloat term=NONE gui=NONE cterm=NONE guifg=NONE ctermfg=NONE guibg=#121212 ctermbg=233 guisp=NONE
hi WhichKeyGroup term=NONE gui=NONE cterm=NONE guifg=#a8a8a8 ctermfg=248 guibg=NONE ctermbg=NONE guisp=NONE
hi WhichKeySeparator term=NONE gui=NONE cterm=NONE guifg=#4e4e4e ctermfg=239 guibg=NONE ctermbg=NONE guisp=NONE
hi Whitespace term=NONE gui=NONE cterm=NONE guifg=#4e4e4e ctermfg=239 guibg=NONE ctermbg=NONE guisp=NONE
hi! link WildMenu PmenuSel
hi WinBar term=bold gui=bold cterm=bold guifg=#a8a8a8 ctermfg=248 guibg=NONE ctermbg=NONE guisp=NONE
hi WinBarNC term=NONE gui=NONE cterm=NONE guifg=#707070 ctermfg=242 guibg=NONE ctermbg=NONE guisp=NONE
hi WinSeparator term=NONE gui=NONE cterm=NONE guifg=#3a3a3a ctermfg=237 guibg=#000000 ctermbg=16 guisp=NONE
hi diffAdded term=NONE gui=NONE cterm=NONE guifg=#1bfd9c ctermfg=49 guibg=NONE ctermbg=NONE guisp=NONE
hi diffChanged term=NONE gui=NONE cterm=NONE guifg=#a8a8a8 ctermfg=248 guibg=NONE ctermbg=NONE guisp=NONE
hi diffFile term=bold gui=bold cterm=bold guifg=#dadada ctermfg=253 guibg=NONE ctermbg=NONE guisp=NONE
hi diffIndexLine term=NONE gui=NONE cterm=NONE guifg=#707070 ctermfg=242 guibg=NONE ctermbg=NONE guisp=NONE
hi diffLine term=NONE gui=NONE cterm=NONE guifg=#a8a8a8 ctermfg=248 guibg=NONE ctermbg=NONE guisp=NONE
hi diffNewFile term=NONE gui=NONE cterm=NONE guifg=#dadada ctermfg=253 guibg=NONE ctermbg=NONE guisp=NONE
hi diffOldFile term=NONE gui=NONE cterm=NONE guifg=#707070 ctermfg=242 guibg=NONE ctermbg=NONE guisp=NONE
hi diffRemoved term=NONE gui=NONE cterm=NONE guifg=#707070 ctermfg=242 guibg=NONE ctermbg=NONE guisp=NONE
hi! link gitcommitComment Comment
hi gitcommitOverflow term=undercurl gui=undercurl cterm=undercurl guifg=#ffffff ctermfg=231 guibg=NONE ctermbg=NONE guisp=#ffffff
hi gitcommitSummary term=bold gui=bold cterm=bold guifg=#dadada ctermfg=253 guibg=NONE ctermbg=NONE guisp=NONE
hi healthError term=bold gui=bold cterm=bold guifg=#ffffff ctermfg=231 guibg=NONE ctermbg=NONE guisp=NONE
hi healthSuccess term=NONE gui=NONE cterm=NONE guifg=#1bfd9c ctermfg=49 guibg=NONE ctermbg=NONE guisp=NONE
hi healthWarning term=NONE gui=NONE cterm=NONE guifg=#a8a8a8 ctermfg=248 guibg=NONE ctermbg=NONE guisp=NONE
hi helpExample term=NONE gui=NONE cterm=NONE guifg=#a8a8a8 ctermfg=248 guibg=NONE ctermbg=NONE guisp=NONE
hi helpHyperTextJump term=NONE gui=NONE cterm=NONE guifg=#1bfd9c ctermfg=49 guibg=NONE ctermbg=NONE guisp=NONE
hi! link lCursor Cursor
hi markdownCode term=NONE gui=NONE cterm=NONE guifg=#a8a8a8 ctermfg=248 guibg=NONE ctermbg=NONE guisp=NONE
hi markdownH1 term=bold gui=bold cterm=bold guifg=#1bfd9c ctermfg=49 guibg=NONE ctermbg=NONE guisp=NONE
hi markdownH2 term=bold gui=bold cterm=bold guifg=#ffffff ctermfg=231 guibg=NONE ctermbg=NONE guisp=NONE
hi markdownH3 term=bold gui=bold cterm=bold guifg=#dadada ctermfg=253 guibg=NONE ctermbg=NONE guisp=NONE
hi markdownUrl term=underline gui=underline cterm=underline guifg=#707070 ctermfg=242 guibg=NONE ctermbg=NONE guisp=NONE

" :terminal, when Vim was built with +terminal
let g:terminal_ansi_colors = ['#1c1c1c', '#a8a8a8', '#00d7af', '#c6c6c6', '#8a8a8a', '#a8a8a8', '#1bfd9c', '#dadada', '#585858', '#c6c6c6', '#1bfd9c', '#dadada', '#a8a8a8', '#c6c6c6', '#87ffd7', '#ffffff']
