--- Generate `colors/quate.vim` from the Lua highlight tables.
---
--- Vim cannot run any of this plugin: it will not source `colors/*.lua`, and
--- its `+lua` has no `vim.api`, no `vim.o`, no `vim.tbl_*`. So the same tables
--- get flattened, once, into plain `:highlight` commands Vim can read.
---
---   nvim -l scripts/gen_vim.lua > colors/quate.vim
---
--- Options are baked in at generation time -- edit `OPTS` below and re-run to
--- change them. Neovim never reads the result; the file hands straight back to
--- `require('quate').load()` when `has('nvim')`.

--- the option set the Vimscript is frozen at
local OPTS = {}

package.path = './lua/?.lua;./lua/?/init.lua;' .. package.path

local config = require('quate.config')
local o = config.setup(OPTS)
local palette = require('quate.palette').get(o)
local groups = require('quate.highlights').setup(palette, o)

--- Vim highlight groups are `[A-Za-z][A-Za-z0-9_]*`; treesitter's `@a.b.c`
--- names and their captures are Neovim's alone.
---@param name string
---@return boolean
local function vim_name(name)
  return name:match('^%a[%w_]*$') ~= nil
end

--- Follow `link` until a real spec turns up, so a group that links into the
--- `@...` namespace still gets its colours in Vim.
---@param spec table
---@return table|nil
local function resolve(spec)
  local seen = 0
  while spec and spec.link do
    if vim_name(spec.link) then
      return spec -- Vim can express this link itself
    end
    seen = seen + 1
    if seen > 16 then
      return nil
    end
    spec = groups[spec.link]
  end
  return spec
end

--- `{ gui, cterm }` pairs, or a bare string like `NONE`
---@param color string|table|nil
---@return string|nil gui
---@return string|nil cterm
local function split(color)
  if type(color) == 'table' then
    return color[1], tostring(color[2])
  elseif type(color) == 'string' then
    return color, color
  end
  return nil, nil
end

local ATTRS = {
  'bold',
  'italic',
  'underline',
  'undercurl',
  'underdouble',
  'underdotted',
  'underdashed',
  'strikethrough',
  'reverse',
  'standout',
  'nocombine',
}

---@param name string
---@param spec table
---@return string
local function command(name, spec)
  if spec.link then
    return ('hi! link %s %s'):format(name, spec.link)
  end

  local args = {}
  local gui_fg, cterm_fg = split(spec.fg)
  local gui_bg, cterm_bg = split(spec.bg)
  local gui_sp = split(spec.sp)

  local attrs = {}
  for _, attr in ipairs(ATTRS) do
    if spec[attr] then
      attrs[#attrs + 1] = attr
    end
  end
  local style = #attrs > 0 and table.concat(attrs, ',') or 'NONE'

  -- Unlike `nvim_set_hl`, Vim's `:highlight` merges into whatever the group
  -- already holds, and `hi clear` restores Vim's *defaults* rather than
  -- emptying them. So every key is written out, `NONE` included, or Search
  -- keeps its default yellow background.
  args[#args + 1] = ('term=%s'):format(style)
  args[#args + 1] = ('gui=%s'):format(style)
  args[#args + 1] = ('cterm=%s'):format(style)
  args[#args + 1] = ('guifg=%s'):format(gui_fg or 'NONE')
  args[#args + 1] = ('ctermfg=%s'):format(cterm_fg or 'NONE')
  args[#args + 1] = ('guibg=%s'):format(gui_bg or 'NONE')
  args[#args + 1] = ('ctermbg=%s'):format(cterm_bg or 'NONE')
  args[#args + 1] = ('guisp=%s'):format(gui_sp or 'NONE')

  return ('hi %s %s'):format(name, table.concat(args, ' '))
end

local names = {}
for name in pairs(groups) do
  if vim_name(name) then
    names[#names + 1] = name
  end
end
table.sort(names)

local out = {}
local function w(line)
  out[#out + 1] = line
end

w('" quate: quiet greys, gruvbox weights, a mint glow.')
w('"')
w('"   :colorscheme quate')
w('"')
w('" GENERATED by scripts/gen_vim.lua -- do not edit. Re-run:')
w('"')
w('"   nvim -l scripts/gen_vim.lua > colors/quate.vim')
w('"')
w('" Neovim keeps the Lua path, with every option and every treesitter and')
w('" diagnostic group. This file is the Vim 8.2+/9 subset: the options are')
w('" frozen at the defaults and the `@...` groups are gone, since Vim has')
w('" neither.')
w('')
w('if has("nvim")')
w("  lua require('quate').load()")
w('  finish')
w('endif')
w('')
w('set background=dark')
w('hi clear')
w('if exists("syntax_on")')
w('  syntax reset')
w('endif')
w("let g:colors_name = 'quate'")
w('')

for _, name in ipairs(names) do
  local spec = resolve(groups[name])
  if spec then
    w(command(name, spec))
  end
end

if o.terminal_colors then
  local ansi = {}
  for _, color in ipairs(palette.terminal) do
    ansi[#ansi + 1] = ("'" .. color[1] .. "'")
  end
  w('')
  w('" :terminal, when Vim was built with +terminal')
  w('let g:terminal_ansi_colors = [' .. table.concat(ansi, ', ') .. ']')
end

w('')
io.write(table.concat(out, '\n'))
